import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/global.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Eric Webb",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav>
					<div>
						<Link href="/">Eric Webb</Link>
					</div>
					<div>
						<Link href="/projects">Projects</Link>
					</div>
					<div>
						<Link href="/contact">Contact</Link>
					</div>
				</nav>
				{children}
			</body>
		</html>
	);
}
